name: linux

on: 
  push:
    paths: 
      - build/**
      - .github/workflows/linux.yml

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          cd build
          ./make_linux_lua54.sh
          ./make_linux64_lua53.sh
          ./make_linux64_luajit.sh
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          path: ./build/plugin_lua54/**/*
          name: plugin_lua54
      - name: Upload53
        uses: actions/upload-artifact@v2
        with:
          path: ./build/plugin_lua53/**/*
          name: plugin_lua53   
      - name: UploadJit
        uses: actions/upload-artifact@v2
        with:
          path: ./build/plugin_luajit/**/*
          name: plugin_luajit 
